version: '3.8'

services:
  web:
    image: python:3.11-slim
    ports:
      - "5000:5000"
    container_name: my_flask_app
    working_dir: /app
    volumes:
      - .:/app
    command: >
      bash -c "
        pip install Flask &&
        echo 'from flask import Flask
app = Flask(__name__)
@app.route(\"/\")
def hello_world():
    return \"Hello, World!\"
if __name__ == '__main__':
    app.run(host=\"0.0.0.0\", port=5000)' > app.py &&
        python app.py
      "

